Raise minSdkVersion to fix lint error
Updating lint exposed new lint errors:
development/samples/AutofillKeyboard/src/com/example/android/autofillkeyboard/AutofillImeService.java:76: Error: Class requires API level 30 (current min is 29): InlineContentClipView [NewApi]
    private InlineContentClipView mScrollableSuggestionsClip;
            ~~~~~~~~~~~~~~~~~~~~~
development/samples/AutofillKeyboard/src/com/example/android/autofillkeyboard/AutofillImeService.java:229: Error: Class requires API level 30 (current min is 29): StylesBuilder [NewApi]
        StylesBuilder stylesBuilder = UiVersions.newStylesBuilder();
        ~~~~~~~~~~~~~

Raise the minSdkVersion to 30 to fix the errors.  Also remove the
lint-baseline.xml, as it only contains errors for APIs introduced in
30.

Bug: 296372320
Test: m lint-check
Change-Id: I2025d056a833cccad1a2b54fdbbdc11112ea62a8